[package]
name = "c2pa-thumbs"
description = "Fetch all thumbs from file with c2pa"
readme = "README.md"
repository = "https://github.com/SmartFrame-Technologies/c2pa-thumbs.git"
keywords = ["c2pa", "thumbnail"]
license = "MIT"
version = "0.2.0"
edition = "2021"

[dependencies]
c2pa = {version="^0.16.0", features=["file_io", "fetch_remote_manifests"]}
base64 = "^0.13.0"
serde = { version = "^1.0.145", features = ["derive"] }
serde_json = "^1.0.86"
